//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Syn.Speech.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Syn.Speech.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///
        ///&lt;config&gt;
        ///
        ///  &lt;property name=&quot;logLevel&quot; value=&quot;INFO&quot;/&gt;
        ///
        ///  &lt;property name=&quot;absoluteBeamWidth&quot;  value=&quot;20000&quot;/&gt;
        ///  &lt;property name=&quot;relativeBeamWidth&quot;  value=&quot;1e-60&quot;/&gt;
        ///  &lt;property name=&quot;absoluteWordBeamWidth&quot;  value=&quot;200&quot;/&gt;
        ///  &lt;property name=&quot;relativeWordBeamWidth&quot;  value=&quot;1e-40&quot;/&gt;
        ///
        ///  &lt;property name=&quot;wordInsertionProbability&quot; value=&quot;0.1&quot;/&gt;
        ///  &lt;property name=&quot;silenceInsertionProbability&quot; value=&quot;0.1&quot;/&gt;
        ///  &lt;property name=&quot;fillerInsertionProbability&quot; value=&quot;1e-2&quot;/&gt;
        ///
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string default_config {
            get {
                return ResourceManager.GetString("default_config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *** Cart dump created by cart_dump
        ///*** Flite version: flite-1.1-release December 2001
        ///*** 
        ///*** Portions Copyright 2001,2002 Sun Microsystems, Inc.
        ///*** Portions Copyright 1999-2001 Language Technologies Institute, 
        ///*** Carnegie Mellon University.
        ///*** All Rights Reserved.  Use is subject to license terms.
        ///*** 
        ///*** See the file &quot;license.terms&quot; for information on usage and
        ///*** redistribution of this file, and for a DISCLAIMER OF ALL 
        ///*** WARRANTIES.
        ///TOTAL 97
        ///NODE num_digits &lt; Float(3.800000) 56
        ///NOD [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string nums_cart {
            get {
                return ResourceManager.GetString("nums_cart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *** fsm dump created by fsm_dump
        ///*** Flite version: flite-1.1-release December 2001
        ///*** 
        ///*** Portions Copyright 2001,2002 Sun Microsystems, Inc.
        ///*** Portions Copyright 1999-2001 Language Technologies Institute, 
        ///*** Carnegie Mellon University.
        ///*** All Rights Reserved.  Use is subject to license terms.
        ///*** 
        ///*** See the file &quot;license.terms&quot; for information on usage and
        ///*** redistribution of this file, and for a DISCLAIMER OF ALL 
        ///*** WARRANTIES.
        ///*** Dumped on Jan 18 2002
        ///
        ///VOCAB_SIZE 128
        ///NUM_OF_T [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string prefix_fsm {
            get {
                return ResourceManager.GetString("prefix_fsm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///
        ///&lt;!--
        ///   Sphinx-4 Configuration file
        ///--&gt;
        ///
        ///&lt;!-- ******************************************************** --&gt;
        ///&lt;!--  spectrogram config file                                 --&gt;
        ///&lt;!-- ******************************************************** --&gt;
        ///
        ///&lt;config&gt;
        ///
        ///
        ///    &lt;!-- ******************************************************** --&gt;
        ///    &lt;!-- The frontend configuration                               --&gt;
        ///    &lt;!-- ********************************************************  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string speakerid_frontend_config {
            get {
                return ResourceManager.GetString("speakerid_frontend_config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *** fsm dump created by fsm_dump
        ///*** Flite version: flite-1.1-release December 2001
        ///*** 
        ///*** Portions Copyright 2001,2002 Sun Microsystems, Inc.
        ///*** Portions Copyright 1999-2001 Language Technologies Institute, 
        ///*** Carnegie Mellon University.
        ///*** All Rights Reserved.  Use is subject to license terms.
        ///*** 
        ///*** See the file &quot;license.terms&quot; for information on usage and
        ///*** redistribution of this file, and for a DISCLAIMER OF ALL 
        ///*** WARRANTIES.
        ///*** Dumped on Jan 18 2002
        ///
        ///VOCAB_SIZE 128
        ///NUM_OF_T [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string suffix_fsm {
            get {
                return ResourceManager.GetString("suffix_fsm", resourceCulture);
            }
        }
    }
}
